### PR TITLE
Re orders members and methods

### PR DESCRIPTION
**Pull request by themoonrat**
1. Class
2. Overrides
3. Inherits

I find this helps reading documentation a lot easier, as it's much quicker to find out what is unique to the class I am looking at, as opposed to wading through the load of members that you get via DisplayObject

http://moonrat.co.uk/html5/pixi-docs/PIXI.Sprite.html
A little sample of this PR (uses the style changes from my other PR https://github.com/pixijs/pixi-jsdoc-template/pull/1 to make it clear the inheritance status of members)
Only includes docs for Sprite / Container / DisplayObject to get an idea of how it works

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
The downside to this approach is that, while it's easier to find the unique items because they are grouped together, the members are not sorted alphabetically, which makes it harder on the whole to browse everything. I have two alternative ideas. Let me know what you think of these:

1. We could so something like this (http://springroll.io/SpringRoll/docs/) I built these docs which have toggle switches at the stop of the page to hide/show the inherited, protected, deprecated items. The settings are saved to localStorage and shared between page views. We could do something like that here (minus private). 
screen shot 2017-09-19 at 3 45 51 pm

2. The other option is doing something more subtle, like bolding the items on the left to note the items unique to this class. For instance:
screen shot 2017-09-19 at 3 51 37 pm

**Comment by bigtimebuddy** [comment]
I added option 2 to master, let me know if you think this is sufficient.

screen shot 2017-09-19 at 5 14 37 pm

**Comment by themoonrat** [comment]
Yeah that's better for PIXI. When I swap our internal api docs to be based off this template, I might add at least one toggle switch for inherited being shown / not shown, just because I think that's a really cool idea I hadn't thought of

**Comment by bigtimebuddy** [comment]
Okay, I'm going to close this for now. Would welcome a PR for the inherited and maybe deprecated toggles.

**Pull request closed without merging**
